package be.davidcorp.loaderSaver;

public enum SpriteProperty {
	SPRITETYPE,
	ID,
	X,
	Y,
	WIDTH,
	HEIGHT, 
	AANTAL_BULLETS, RED, GREEN, BLUE, RADIUS, LIGHTON, STAMINA, ATTACKDAMAGE, WEIGHT, INFOTEXT, USABLERANGE, TIME_TO_LIVE;
}
