package be.davidcorp.domain.sprite;

public enum SpriteType {
	ENEMY, 
	WALL, 
	ZOMBIE, 
	SPIDER, 
	PISTOL,
	AX, 
	DOOR, 
	HEALTHPOTION, 
	STAMINAPOTION, 
	LIGHT, BULLET, GEAR, GUIDEAREA, HEALTHNECKLACE, PLAYER, ROCKET, ROCKETLAUNCHER, SWINGAREA, CONSTRUCTION, ITEM, SPRITESPAWNER, MISC, DESK;
}
